### PR TITLE
Docs: Documented the Workflow 

### PR DESCRIPTION
**Pull request by JeelDobariya38**
**TL;DR**: Add Documentation

## Changes Made
- add description in **README.md**
- document the **release process** and **database design**
- all other documents.

### CODE REVIEW

**Review by kudanilll — CHANGES_REQUESTED** [review]
hmm, the commit is 'add docs', but files changes is not docs.

**Comment by JeelDobariya38** [comment]
Wait I am doing!!

**Comment by JeelDobariya38** [comment]
It is under development not ready to review

**Review by kudanilll — APPROVED** [review]
I changed some files to make it more organized (README.md & database-design.md)

**Comment by JeelDobariya38** [comment]
Please add your personal email in the Security policy @achmaddaniel24 @HamadaNative

**Review by ghost — COMMENTED** [review]
Why are you deleting the .idea is that for C.A

**Comment by JeelDobariya38** [comment]
Yes, it was done to avoid conflict.

**Comment by kudanilll** [comment]
> Please add your personal email in the Security policy @achmaddaniel24 @HamadaNative

okay

**Review by kudanilll — APPROVED** [review]
good documentation design!

**Review by ghost — APPROVED** [review]
Ok. I don't see anything wrong.

**Pull request merged**
